// Static, localized UI strings (greetings, errors, footers). These are NOT
// generated by the AI, so they are translated by hand here. Dynamic answers are
// produced by Gemini in the user's exact language.
//
// Keys per string: uz_latn, uz_cyrl, kk (Karakalpak Latin), ru, other (a short
// trilingual fallback used when we can't detect the language statically).

const SERVICES_UZ = [
  '• 🛂 Xorijga chiqish biometrik pasport',
  '• 🪪 ID-karta',
  '• 🏠 Yashash / turar joy bo‘yicha ro‘yxatga olish (propiska)',
  '• 🌍 Chet el fuqarolarini vaqtincha ro‘yxatga olish',
  '• 📜 Fuqarolikni qabul qilish va undan chiqish',
  '• ✉️ Taklifnoma (mehmon chaqiruvi)',
  '• 📞 Tuman/shahar bo‘limlari bog‘lanish raqamlari',
].join('\n');

const SERVICES_RU = [
  '• 🛂 Биометрический паспорт для выезда за границу',
  '• 🪪 ID-карта',
  '• 🏠 Регистрация по месту жительства / пребывания (прописка)',
  '• 🌍 Временная регистрация иностранных граждан',
  '• 📜 Приём и выход из гражданства',
  '• ✉️ Приглашение (Taklifnoma)',
  '• 📞 Контактные телефоны районных/городских отделов',
].join('\n');

const SERVICES_KK = [
  '• 🛂 Sırt elge shığıw biometrik pasporti',
  '• 🪪 ID-karta',
  '• 🏠 Jasaw / turaq jay boyınsha dizimge alıw (propiska)',
  '• 🌍 Shet el puqaralarin waqtınsha dizimge alıw',
  '• 📜 Puqaralıqtı qabıl etiw hám shığıw',
  '• ✉️ Shaqırıw qағazı (Taklifnoma)',
  '• 📞 Rayon/qala bólimleriniń baylanıs telefonları',
].join('\n');

// Shown on /start, before we know the user's language — so it's trilingual.
export const LANG_PROMPT =
  '🌐 Iltimos, tilni tanlang:\n' +
  'Tildi saylań:\n' +
  'Пожалуйста, выберите язык:';

// Language-selection buttons. `code` matches our internal language keys.
// No emoji for Karakalpak: there is no Unicode flag for it, and a stand-in
// symbol would be disrespectful. The real Karakalpakstan flag is shown as the
// banner image above the buttons instead.
export const LANG_BUTTONS = [
  { code: 'uz_latn', label: '🇺🇿 Oʻzbekcha' },
  { code: 'kk', label: 'Qaraqalpaqsha' },
  { code: 'ru', label: '🇷🇺 Русский' },
];

export const UI = {
  welcome: {
    uz_latn:
      'Assalomu alaykum! 👋\n' +
      'Men Migratsiya va personallashtirish bo‘limi xizmatlari bo‘yicha rasmiy yordamchi botman.\n\n' +
      'Quyidagi mavzularda savol bera olasiz:\n' +
      SERVICES_UZ +
      '\n\nSavolingizni o‘zbek, qoraqalpoq yoki rus tilida yozing — men tilni o‘zim aniqlayman.',
    uz_cyrl:
      'Ассалому алайкум! 👋\n' +
      'Мен Миграция ва персоналлаштириш бўлими хизматлари бўйича расмий ёрдамчи ботман.\n\n' +
      'Қуйидаги мавзуларда савол бера оласиз:\n' +
      '• 🛂 Хорижга чиқиш биометрик паспорт\n• 🪪 ID-карта\n• 🏠 Яшаш/турар жой бўйича рўйхатга олиш (прописка)\n• 🌍 Чет эл фуқароларини вақтинча рўйхатга олиш\n• 📜 Фуқароликни қабул қилиш ва чиқиш\n• ✉️ Таклифнома' +
      '\n\nСаволингизни ўзбек, қорақалпоқ ёки рус тилида ёзинг.',
    kk:
      'Assalawma aleykum! 👋\n' +
      'Men Migratsiya hám personallastırıw bólimi xızmetleri boyınsha rásmiy járdemshi botpan.\n\n' +
      'Tómendegi temalar boyınsha soraw bere alasız:\n' +
      SERVICES_KK +
      '\n\nSorawıńızdı ózbek, qaraqalpaq yamasa rus tilinde jazıń — tildi ózim anıqlayman.',
    ru:
      'Здравствуйте! 👋\n' +
      'Я официальный бот-помощник по услугам Отдела миграции и оформления гражданства.\n\n' +
      'Вы можете задать вопрос по темам:\n' +
      SERVICES_RU +
      '\n\nНапишите вопрос на узбекском, каракалпакском или русском языке — язык я определю сам.',
    other:
      '👋 Assalomu alaykum! / Здравствуйте! / Assalawma aleykum!\n\n' +
      'Men pasport va migratsiya xizmatlari bo‘yicha yordamchi botman.\n' +
      'Я бот-помощник по паспортным и миграционным услугам.\n\n' +
      'Savolingizni o‘zbek, qoraqalpoq yoki rus tilida yozing.\n' +
      'Напишите вопрос на узбекском, каракалпакском или русском языке.',
  },

  help: {
    uz_latn:
      'ℹ️ Shunchaki savolingizni yozing — men tilni avtomatik aniqlab, o‘sha tilda javob beraman.\n\n' +
      'Men quyidagi mavzular bo‘yicha yordam beraman:\n' +
      SERVICES_UZ +
      '\n\nBuyruqlar:\n/start — boshlash\n/help — yordam',
    uz_cyrl:
      'ℹ️ Шунчаки саволингизни ёзинг — мен тилни аниқлаб, ўша тилда жавоб бераман.\n\n' +
      'Буйруқлар:\n/start — бошлаш\n/help — ёрдам',
    kk:
      'ℹ️ Sorawıńızdı jazıń — men tildi ózim anıqlap, sol tilde juwap beremen.\n\n' +
      'Men tómendegi temalar boyınsha járdem beremen:\n' +
      SERVICES_KK +
      '\n\nBuyrıqlar:\n/start — baslaw\n/help — járdem',
    ru:
      'ℹ️ Просто напишите ваш вопрос — я сам определю язык и отвечу на нём.\n\n' +
      'Я помогаю по темам:\n' +
      SERVICES_RU +
      '\n\nКоманды:\n/start — начать\n/help — помощь',
    other:
      'ℹ️ Savolingizni yozing / Напишите ваш вопрос / Sorawıńızdı jazıń.\n' +
      'O‘zbek, qoraqalpoq yoki rus tilida. / На узбекском, каракалпакском или русском.',
  },

  // Appended to a best-guess answer when the model was unsure due to dialect/typos.
  footerClarify: {
    uz_latn:
      '\n\n⚠️ Savolingizni aniq tushunishim uchun, iltimos, uni rasmiy o‘zbek yoki qoraqalpoq tilida aniqroq yozib yuboring.',
    uz_cyrl:
      '\n\n⚠️ Саволингизни аниқ тушунишим учун, илтимос, уни расмий ўзбек ёки қорақалпоқ тилида аниқроқ ёзиб юборинг.',
    kk:
      '\n\n⚠️ Sorawıńızdı anıq túsiniwim ushın, ótinish, onı rásmiy qaraqalpaq yamasa ózbek tilinde anığıraq jazıp jiberiń.',
    ru:
      '\n\n⚠️ Чтобы я мог точно понять ваш вопрос, пожалуйста, напишите его чётче на официальном узбекском или каракалпакском языке.',
    other:
      '\n\n⚠️ Iltimos, savolni o‘zbek, qoraqalpoq yoki rus tilida yozing. / Пожалуйста, напишите вопрос на узбекском, каракалпакском или русском языке.',
  },

  nonText: {
    uz_latn:
      'Men faqat matnli savollarga javob bera olaman. Iltimos, savolingizni matn ko‘rinishida yozing. 🙏',
    uz_cyrl:
      'Мен фақат матнли саволларга жавоб бера оламан. Илтимос, саволингизни матн кўринишида ёзинг. 🙏',
    kk:
      'Men tek matnlı sorawlarǵa juwap bere alaman. Ótinish, sorawıńızdı matn túrinde jazıń. 🙏',
    ru:
      'Я могу отвечать только на текстовые вопросы. Пожалуйста, напишите ваш вопрос текстом. 🙏',
    other:
      'Iltimos, savolni matn ko‘rinishida yozing. / Пожалуйста, напишите вопрос текстом. 🙏',
  },

  error: {
    uz_latn:
      'Kechirasiz, texnik nosozlik yuz berdi. Iltimos, biroz vaqtdan so‘ng qayta urinib ko‘ring. 🙏',
    uz_cyrl:
      'Кечирасиз, техник носозлик юз берди. Илтимос, бироз вақтдан сўнг қайта уриниб кўринг. 🙏',
    kk:
      'Keshiriń, texnikalıq qátelik júz berdi. Ótinish, azǵantay waqıttan keyin qayta urınıp kóriń. 🙏',
    ru:
      'Извините, произошла техническая ошибка. Пожалуйста, попробуйте ещё раз чуть позже. 🙏',
    other:
      'Texnik nosozlik. Keyinroq urinib ko‘ring. / Техническая ошибка. Попробуйте позже. 🙏',
  },

  rateLimited: {
    uz_latn:
      'Siz juda tez-tez yozmoqdasiz. Iltimos, bir daqiqa kutib, qayta urinib ko‘ring. ⏳',
    uz_cyrl:
      'Сиз жуда тез-тез ёзмоқдасиз. Илтимос, бир дақиқа кутиб, қайта уриниб кўринг. ⏳',
    kk:
      'Siz júdá tez-tez jazıp atırsız. Ótinish, bir minut kútip, qayta urınıp kóriń. ⏳',
    ru:
      'Вы пишете слишком часто. Пожалуйста, подождите минуту и попробуйте снова. ⏳',
    other:
      'Juda tez yozyapsiz, biroz kuting. / Слишком часто, подождите минуту. ⏳',
  },

  blocked: {
    uz_latn: 'Sizning ushbu botdan foydalanishingiz cheklangan.',
    uz_cyrl: 'Сизнинг ушбу ботдан фойдаланишингиз чекланган.',
    kk: 'Sizdiń bul bottan paydalanıwıńız sheklengen.',
    ru: 'Ваш доступ к этому боту ограничен.',
    other: 'Foydalanish cheklangan. / Доступ ограничен.',
  },

  adminOnly: {
    uz_latn: '⛔️ Bu buyruq faqat administratorlar uchun.',
    uz_cyrl: '⛔️ Бу буйруқ фақат администраторлар учун.',
    kk: '⛔️ Bul buyrıq tek administratorlar ushın.',
    ru: '⛔️ Эта команда доступна только администраторам.',
    other: '⛔️ Faqat adminlar uchun. / Только для администраторов.',
  },
};

/** Pick a localized string, falling back to the trilingual `other` then uz_latn. */
export function t(key, lang) {
  const group = UI[key] || {};
  return group[lang] || group.other || group.uz_latn || '';
}

/**
 * Best-effort language guess for STATIC messages (commands, errors) where we
 * have no AI detection yet — based on Telegram's reported client language code.
 */
export function staticLang(code) {
  if (!code) return 'other';
  const c = code.toLowerCase();
  if (c.startsWith('ru')) return 'ru';
  if (c.startsWith('kaa')) return 'kk';
  if (c.startsWith('uz')) return 'uz_latn';
  return 'other';
}
